### ISSUE TITLE
Missing field Fhp\Segment\SAL\HISALv7.buchungszeitpunkt

### ISSUE THREAD

**Issue by Hunzlifuz** [nemiah/phpFinTS#304]
Hi,
i don't know if i am doing anything wrong but if I just want to test the samples I am getting an error when I want do download the saldo of my account.
Everything else works fine but the saldo always returns with error.
I am using the latest version and testet the old sample-File "saldo.php" with my banking credentials. I testet it with two different banks (Raiffeisenbank Bayern Mitte 72160818 and DKB 12030000) with the same result.
Also with the FinTsNew and the new approach in SamplesNew i get this error.

Uncaught InvalidArgumentException: Missing field Fhp\Segment\SAL\HISALv7.buchungszeitpunkt in \FinTS\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php:322 Stack trace: #0 \FinTS\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(438): Fhp\Syntax\Parser::parseSegment('HISAL:5:7:3+DE6...', 'Fhp\\Segment\\SAL...') #1 [internal function]: Fhp\Syntax\Parser::detectAndParseSegment('HISAL:5:7:3+DE6...') #2 \FinTS\vendor\nemiah\php-fints\lib\Fhp\Syntax\Parser.php(455): array_map(Array, Array) #3 \FinTS\vendor\nemiah\php-fints\lib\Fhp\Protocol\Message.php(319): Fhp\Syntax\Parser::parseSegments(Array) #4 \FinTS\vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php(875): Fhp\Protocol\Message::parse('HNHBK:1:3+00000...') #5 \FinTS\vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php(339): Fhp\FinTsNew->sendMessage(Object(Fhp\Protocol\Message)) #6 \FinTS\vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php(298): Fhp\FinTsNew->sendRequestForAction(Object(Fhp\Action\ in \FinTS\vendor\nemiah\php-fints\lib\Fhp\FinTsNew.php on line 877

**Comment by Hunzlifuz** [comment]
Short Update.
I did further testing and it is working for bank DKB.
But for Raiffeisenbank Bayern Mitte (72160818) and norisbank (10077777) the exception above is thrown.

**Comment by Hunzlifuz** [comment]
Short Update.
For Raiffeisenbank it is enough to comment out the variable $buchungszeitpunkt in File Fhp\Segment\SAL\HISALv7
then it works for this bank
But for norisbank it seems the wrong version of HISAL. It also throws an error for kontoverbindungInternational and kontoproduktbezeichnung. Then i stopped testing.

**Comment by Philipp91** [comment]
This was [fixed](https://github.com/nemiah/phpFinTS/commit/2b2e1b314e3e14f3e8d34ce2cd7bcf2b6f6a331f) already. Please use code from the `master` branch for now (`dev-master` in Composer). @nemiah I think it would be helpful if we could release a new version, so that people can use the latest code more easily and don't spend their time debugging issues that have been fixed already.

**Comment by nemiah** [comment]
Sure, shall I use the current state or do you have something to add?

**Comment by Philipp91** [comment]
I don't have any outstanding commits on my side and I couldn't find any open issues that would block a release. There is an open draft pull request that would add a new feature, but that can always be added in a subsequent (non-breaking) release.

**Comment by Hunzlifuz** [comment]
Hi, thanks for the quick response. For Raiffeisenbank and DKB its now working fine.
But with norisbank i am still getting the error:

Uncaught InvalidArgumentException: Missing field Fhp\\Segment\\SAL\\HISALv7.kontoverbindungInternational in D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\Syntax\\Parser.php:322\nStack trace:\n#0 D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\Syntax\\Parser.php(438): Fhp\\Syntax\\Parser::parseSegment('HISAL:4:7:3++no...', 'Fhp\\\\Segment\\\\SAL...')\n#1 [internal function]: Fhp\\Syntax\\Parser::detectAndParseSegment('HISAL:4:7:3++no...')\n#2 D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\Syntax\\Parser.php(455): array_map(Array, Array)\n#3 D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\Protocol\\Message.php(319): Fhp\\Syntax\\Parser::parseSegments(Array)\n#4 D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\FinTs.php(851): Fhp\\Protocol\\Message::parse('HNHBK:1:3+00000...')\n#5 D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\FinTs.php(306): Fhp\\FinTs-&gt;sendMessage(Object(Fhp\\Protocol\\Message))\n#6 D:\\workspace\\openui5.hunzlifuz. in <b>D:\\workspace\\openui5.hunzlifuz.de\\vendor\\nemiah\\php-fints\\lib\\Fhp\\FinTs.php

**Comment by Hunzlifuz** [comment]
For my testing i downloaded the dev-master via composer

**Comment by Philipp91** [comment]
Oh okay, that's another, more subtle bug. As can be seen from your error message, the `HISAL` segment has an empty second group (`HISAL:4:7:3++no...` -- between the two pluses). The `Kti` field itself is mandatory, but all of the fields within the `Kti` type are optional, so an empty group is technically allowed. This will have to be fixed in the parser itself, for which I prefer strong unit tests. Could you please somehow log (with `SanitizingLogger`) or otherwise intercept (e.g. `echo` or a breakpoint in your IDE) the segment contents as they go over the wire, i.e. filling in the `...` above? Feel free to change the balance itself to 1234  or so.

**Comment by Hunzlifuz** [comment]
I hope the attached file contains the relevant information for you.
[HISAL_err.txt](https://github.com/nemiah/phpFinTS/files/5082240/HISAL_err.txt)
